### ISSUE TITLE
Add a way to configure the so version independent of the crate version

### ISSUE THREAD

**Issue by sdroege** [lu-zero/cargo-c#100]
See summary. The C API does not necessarily break whenever the Rust one does, and in my case I need this for configuring the same version as an existing C library.

**Comment by sdroege** [comment]
Maybe some kind of

```
[package.metadata.capi]
library_name = "libebur128"
library_version = "1.2.4"
```

That would also allow for the common pattern in C libraries to have the API version as part of the library name (`libglib-2.0.so.0`).

Once decided on a way to configure it, I can implement it.

**Comment by lu-zero** [comment]
It is fine for me, as long the default remains streamlined, any customization can be allowed.

**Comment by sdroege** [comment]
Yeah the goal is to have everything behave like it does now by default and only if someone actually provides these configurations it would change.
