### ISSUE TITLE
Rebuilds pkg-config file on `cbuild` and `cinstall`

### ISSUE THREAD

**Issue by sdroege** [lu-zero/cargo-c#104]
```
$ cargo cbuild --prefix=(pwd)/install
   Compiling ebur128 v0.1.1 (/home/slomo/Projects/rust/ebur128)
    Finished dev [optimized + debuginfo] target(s) in 2.84s
    Building pkg-config file
$ cargo cinstall --prefix=(pwd)/install
    Finished dev [optimized + debuginfo] target(s) in 2.02s
    Building pkg-config file
  Installing pkg-config file
  Installing header file
  Installing static library
  Installing shared library
```

It seems like it also re-links (or even rebuilds) the library itself. If this can't be reproduced with anything else then I'll debug this / provide a testcase in a bit.

**Comment by sdroege** [comment]
Reason for that is that only the actual library is part of what is fingerprinted in `src/build.rs`.

**Comment by lu-zero** [comment]
Did you have time to look into it?

**Comment by sdroege** [comment]
Yes, see above. There's simply not caching for the pkg-config file generated implemented.

**Comment by gdesmott** [comment]
I fixed that as it's quite annoying when rebuilding all the GStreamer plugins :) https://github.com/lu-zero/cargo-c/pull/145
