### ISSUE TITLE
Install C header file without additional sub-directory?

### ISSUE THREAD

**Issue by mgeier** [lu-zero/cargo-c#125]
AFAICT, currently the C header file will be unconditionally installed into a sub-directory.
For example, if the library is called `asdf`, the header file will be installed to `/usr/local/include/asdf/asdf.h` per default.

I think it would be easier to use if it would be installed without the extra sub-directory, i.e. to `/usr/local/include/asdf.h`.

Having a sub-directory would only really make sense if there were multiple header files, but `cargo-c` doesn't create multiple header files anyway, right?

Without the sub-directory (and assuming the library was installed in the default location), the header can be included like this:

```c
#include <asdf.h>
```

... while with the sub-directory it works with

```c
#include <asdf/asdf.h>
```

... which I think is less typical for a single-header library.

I know that `pkg-config` can be used to obtain the `--cflags` which contain the sub-directory. While this works, it would be even better if it would simply work without `pkg-config` (again, assuming installation to the default location).

I think in C libraries with multiple headers it is actually very common to use the sub-directory in the `#include`, for example in [`libFLAC`](https://github.com/xiph/flac):

```c
#include "FLAC/stream_decoder.h"
```

This means that `pkg-config --cflags` would actually *not* contain the `FLAC` sub-directory!

So, in a way, `cargo-c` including the sub-directory can be seen as an error (or at least as non-typical behavior).

Also, there is really no advantage in having an extra sub-directory (for a single header file), right?

I think it would be best if `cargo-c` would install the header file without extra sub-directory, but I guess this would be a backward-incompatible change.

So maybe this could be provided as a command line flag?

See also #122 for some initial discussion.

**Comment by Luni-4** [comment]
@mgeier 

Forgot to ask you that in the PR, but have you tried to add `subdirectory = false` under the `package.metadata.capi.header` in your `Cargo.toml`?

**Comment by mgeier** [comment]
No, I didn't know that option! Thanks for the hint!

That solves part of the problem, and I've already applied it to the example project: #130.

I think this really should have been the default setting ...
But at least now (when #130 is merged) it is part of the example project's setup.

There is still a problem left though:
Even when using a sub-directory, this should not be part of the path returned by `pkg-config --cflags`, as mentioned in my comment above.
The sub-directory should be part of the `#include`.

**Comment by Luni-4** [comment]
> I think this really should have been the default setting ...

@lu-zero  What do you think about making `subdirectory = false` the default behaviour? 

> There is still a problem left though:
> Even when using a sub-directory, this should not be part of the path returned by `pkg-config --cflags`, as mentioned in my comment above.
> The sub-directory should be part of the `#include`.

To do so, we need to modify [here](https://github.com/lu-zero/cargo-c/blob/master/src/pkg_config_gen.rs#L61). Perhaps we should add another field to the `package.metadata.capi.header`. @lu-zero what do you think about this alternative?

**Comment by lu-zero** [comment]
> > I think this really should have been the default setting ...
> 
> @lu-zero
> What do you think about making `subdirectory = false` the default behaviour?

The headers in a separate directory makes much easier to have parallel implementations (versioned or alternate impl). The default should be the most future proof choice.

> > There is still a problem left though:
> > Even when using a sub-directory, this should not be part of the path returned by `pkg-config --cflags`, as mentioned in my comment above.
> > The sub-directory should be part of the `#include`.

See the comment above, it would defeat its purpose.

> To do so, we need to modify [here](https://github.com/lu-zero/cargo-c/blob/master/src/pkg_config_gen.rs#L61). Perhaps we should add another field to the `package.metadata.capi.header`. What do you think about this alternative, @lu-zero?

I would reject that change, sorry.

**Comment by Luni-4** [comment]
> The headers in a separate directory makes much easier to have parallel implementations (versioned or alternate impl). The default should be the most future proof choice.

I agree, anyway it's not a problem because the metadata field is well documented and anyone can change it whenever he wants.

 
> > To do so, we need to modify [here](https://github.com/lu-zero/cargo-c/blob/master/src/pkg_config_gen.rs#L61). Perhaps we should add another field to the `package.metadata.capi.header`. What do you think about this alternative, @lu-zero?
> 
> I would reject that change, sorry.

Ok, it seems legit to me, in the end it's just a stylistic style not a wrong choice. Closing this issue.
