### ISSUE TITLE
Linking failure

### ISSUE THREAD

**Issue by cschwan** [lu-zero/cargo-c#126]
I think I found a regression; I've updated `cargo-c` today, and tried to compile and install [`pineappl_capi`](https://github.com/N3PDF/pineappl/tree/master/pineappl_capi) with it, which fails to link with the following error:

       Compiling pineappl_capi v0.3.0 (/home/cschwan/projects/pineappl/pineappl_capi)
    error: linking with `x86_64-pc-linux-gnu-gcc` failed: exit code: 1
      |
      = note: "x86_64-pc-linux-gnu-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-plugin-opt=O3" "-Wl,-plugin-opt=mcpu=x86-64" "-L" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.0.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.1.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.10.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.11.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.12.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.13.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.14.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.15.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.2.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.3.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.4.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.5.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.6.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.7.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.8.rcgu.o" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.9.rcgu.o" "-o" "/home/cschwan/projects/pineappl/target/release/deps/libpineappl_capi-2b97f5920702027d.so" "-Wl,--version-script=/tmp/rustcM01doQ/list" "/home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.49cfc9at39dsf638.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/cschwan/projects/pineappl/target/release/deps" "-L" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/cschwan/projects/pineappl/target/release/deps/libpineappl-4472323a425eb92a.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libbincode-2e9f8d8fbd7417bb.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libanyhow-822fa536faa48023.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libarrayvec-4eef94c5c2341f35.rlib" "/home/cschwan/projects/pineappl/target/release/deps/librustc_hash-a03740381bfef860.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libndarray-4b5522cf2c7e9fea.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libmatrixmultiply-6b4d0d42f6ab122f.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libnum_complex-cd488380df2f8203.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libnum_integer-fbb39f23c49945ab.rlib" "/home/cschwan/projects/pineappl/target/release/deps/librawpointer-0611211f8630c294.rlib" "/home/cschwan/projects/pineappl/target/release/deps/liblz_fear-9ac0901220c1a23f.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libbitflags-c04e349225fc0ffb.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libtwox_hash-1db59d38a4875dc6.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libfehler-ddcfdb7d35fb782d.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libbyteorder-ead1804dbb54dadc.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libthiserror-535168a6af64a1f6.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libserde-03e6c9c8d2c27af4.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libfloat_cmp-1262eddf55a55682.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libnum_traits-1ce00c1f7faed7d0.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libitertools-434ad0d079f98aec.rlib" "/home/cschwan/projects/pineappl/target/release/deps/libeither-2e3e845537d9dd1a.rlib" "-Wl,--start-group" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libstd-d74c871aa1a49564.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-fbd00f445b7d4263.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-9cd57ef920264fa0.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-25a159709f8922a6.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-543794fbbd9ff6fa.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-1ec9c2a67cc1187b.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0f362339e8563263.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5dc16c13c8c78e9a.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8f56e6611a96b11e.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-d6df24fb977ba40a.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c848199df5039aa8.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-38ad54a9cfd227e6.rlib" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libcore-8c172ed7091d26c1.rlib" "-Wl,--end-group" "/usr/lib64/rust-1.46.0/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f483f6f625149722.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil" "-Wl,-soname,libpineappl_capi.so.0"
      = note: /home/cschwan/projects/pineappl/target/release/deps/pineappl_capi-2b97f5920702027d.pineappl_capi.ccegopd2-cgu.0.rcgu.o: file not recognized: file format not recognized
              collect2: error: ld returned 1 exit status
    
    
    error: aborting due to previous error
    
    Error: CliError { error: Some(could not compile `pineappl_capi`.
    
    Caused by:
        process didn't exit successfully: `rustc --crate-name pineappl_capi --edition=2018 pineappl_capi/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C linker-plugin-lto -C link-arg=-Wl,-soname,libpineappl_capi.so.0 --cfg cargo_c -C metadata=2b97f5920702027d -C extra-filename=-2b97f5920702027d --out-dir /home/cschwan/projects/pineappl/target/release/deps -L dependency=/home/cschwan/projects/pineappl/target/release/deps --extern itertools=/home/cschwan/projects/pineappl/target/release/deps/libitertools-434ad0d079f98aec.rlib --extern pineappl=/home/cschwan/projects/pineappl/target/release/deps/libpineappl-4472323a425eb92a.rlib` (exit code: 1)), exit_code: 101 }

Previous versions used to work, so I tried to `git bisect` the error which is blaming commit e1b15b7301b23f5aacfcd92cd21793f2552f6252. I don't understand enough of the internal to further investigate, but please let me know if you need more information. I am using rust 1.46.0 which is the current version in gentoo.

**Comment by lu-zero** [comment]
It seems to happen randomly I managed to reproduce it only once, once I tried to clean and rebuild it, it works.

Can you please tell me if that file is truncated?

**Comment by cschwan** [comment]
Which file? The `*.0.rcgu.o` file whose file format isn't recognised is binary, so I can't tell. Running `file` on it says `LLVM IR bitcode`, however. It's interesting that it happens randomly for you, here it fails 10 times out of 10.

**Comment by lu-zero** [comment]
Can we discuss on zulip? it is really fishy and going back and forth on the issue might be non-optimal.

**Comment by cschwan** [comment]
Yes, I've never used it before, but I'm sure I can figure it out!

**Comment by lu-zero** [comment]
If this works for you I'd make a fix release with this and the I'd try to debug it later

**Comment by cschwan** [comment]
Alright. I suppose if we want to discuss on zulip you'll send me a link? In that case go ahead.

**Comment by lu-zero** [comment]
It is also present in the readme -> [zulip chat](https://rust-av.zulipchat.com/#narrow/stream/254255-cargo-c)

**Comment by cschwan** [comment]
Sorry, I missed the badge, but I'm in now.

**Comment by lu-zero** [comment]
I published a version with the previous cargo, I'll figure out later why cargo is trying to feed cc the lto .o

**Comment by cschwan** [comment]
Thanks a lot!

**Comment by lu-zero** [comment]
So, now I have time to track what's going on:
cargo-45 does:
```
rustc --crate-name pineappl_capi --edition=2018 pineappl_capi/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C lto -C link-arg=-Wl,-soname,libpineappl_capi.so.0 --cfg cargo_c -C metadata=1d51455ae41b66fe --out-dir /home/lu_zero/Sources/pineappl/target/release/deps -L dependency=/home/lu_zero/Sources/pineappl/target/release/deps --extern itertools=/home/lu_zero/Sources/pineappl/target/release/deps/libitertools-5a382b4f7fb927b0.rlib --extern pineappl=/home/lu_zero/Sources/pineappl/target/release/deps/libpineappl-2556242f8941ece1.rlib
```
cargo-49 does:
```
rustc --crate-name pineappl_capi --edition=2018 pineappl_capi/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C lto -C link-arg=-Wl,-soname,libpineappl_capi.so.0 --cfg cargo_c -C metadata=1d51455ae41b66fe --out-dir /home/lu_zero/Sources/pineappl/target/release/deps -L dependency=/home/lu_zero/Sources/pineappl/target/release/deps --extern itertools=/home/lu_zero/Sources/pineappl/target/release/deps/libitertools-5a382b4f7fb927b0.rlib --extern pineappl=/home/lu_zero/Sources/pineappl/target/release/deps/libpineappl-2556242f8941ece1.rlib
```

so one does `-C lto` and works the other uses `-C linker-plugin-lto` and fails.
