### ISSUE TITLE
"cargo install cargo-c" picks the wrong version

### ISSUE THREAD

**Issue by mgeier** [lu-zero/cargo-c#129]
There seems to be some confusion which is the latest version ...

```
$ cargo install cargo-c
    Updating crates.io index
  Downloaded cargo-c v0.6.15
error: failed to verify the checksum of `cargo-c v0.6.15`
```

When I explicitly specify the latest version, everything works fine:

    cargo install cargo-c --version 0.6.15+cargo-0.45

**Comment by lu-zero** [comment]
I bumped the version to avoid this. Thank you for reporting!

**Comment by mgeier** [comment]
Thanks a lot! I can confirm that now it works again.
