### ISSUE TITLE
Generates functions outside of capi.rs

### ISSUE THREAD

**Issue by Enulp** [lu-zero/cargo-c#133]
Link for the example: https://gitlab.com/enulp/cargo-c-test

As I understand cargo-c expose the C-API from functions inside `capi.rs`
But in the example above it also generates function from the `sys.rs` file.
Is it normal?

**Comment by lu-zero** [comment]
It generates C definitions for every public function or struct that is C-compatible, it is not limited to a specific file.

**Comment by Enulp** [comment]
Is there a way to specify a file?

**Comment by lu-zero** [comment]
Not explicitly.

Please refer to the [cbindgen manual](https://github.com/eqrion/cbindgen/blob/master/docs.md), I'm not sure what are you trying to achieve, but maybe you'll find a way.

cargo-c uses cbindgen to generate the header.

**Comment by Enulp** [comment]
Thanks for your help

The solution was explained in https://github.com/eqrion/cbindgen/issues/484.
I needed to remove `pub`from `pub mod sys` and add `/// cbindgen:ignore` behind it in `lib.rs`

**Comment by lu-zero** [comment]
I guess this issues can be closed now?
