### ISSUE TITLE
dumpbin is not in the PATH by default

### ISSUE THREAD

**Issue by Mikayex** [lu-zero/cargo-c#147]
I'm currently trying to add cargo-c to a project and I'm compiling with MSVC.

The problem is that `dumpbin` is not in the PATH by default. This has been mentioned in  #113 and added in #71.

I've the following error:
```
    Building pkg-config file
    Building .def file using dumpbin
Error: CliError { error: Some(The system cannot find the file specified. (os error 2)), exit_code: 101 }
```

As a workaround I could add `dumpbin` manually to the PATH, which I find ugly. Or maybe use a `build.rs` to find `dumpbin` and add it to the PATH, which is not ideal too.

Maybe the linker path information obtained from cargo can be used since (at least for VS 2019) `dumpbin.exe` is in the same directory as `link.exe` and `cl.exe` ?

**Comment by Mikayex** [comment]
Also `cc::windows_registry::find_tool` can find `dumpbin` correctly on my machine.

**Comment by lu-zero** [comment]
Potentially we could bring-in CC and use it to get the path of the different tools we use. I'd welcome a patch if you have time since windows isn't my favourite platform.
