### ISSUE TITLE
Renaming the library is broken

### ISSUE THREAD

**Issue by cschwan** [lu-zero/cargo-c#166]
Renaming the library and the pkg-config file seems to be broken. I can only rename the header using `package.metadata.capi.header` in `Cargo.toml`. If I try to use

    [package]
    name = "a"

    [package.metadata.capi.library]
    name = "b"

to rename the library I get

       Compiling a v0.1.0 (/tmp/a)
        Finished dev [unoptimized + debuginfo] target(s) in 0.08s
        Building pkg-config file
        Building pkg-config file
        Building header file using cbindgen
    Error: CliError { error: Some(Cannot copy /tmp/a/target/./debug/libb.so to /tmp/a/target/./debug/libb.so.0.1.0.

    Caused by:
        No such file or directory (os error 2)), exit_code: 101 }

It seems the first path is wrong.

Finally `package.metadata.capi.pkg_config` seems to be ignored. The content of the `*.pc` seems to be correct though:

    prefix=/usr/local
    exec_prefix=${prefix}
    libdir=${exec_prefix}/lib
    includedir=${prefix}/include

    Name: b
    Description: 
    Version: 0.1.0
    Libs: -L${libdir} -lb
    Cflags: -I${includedir}/a
    Libs.private: -lgcc_s -lutil -lrt -lpthread -lm -ldl -lc

The complete MWE is here: https://gist.github.com/cschwan/0cb317b682541ed6962dcab65cda1b7a

**Comment by sdroege** [comment]
> Finally `package.metadata.capi.pkg_config` seems to be ignored. The content of the `*.pc` seems to be correct though:

What do you mean with ignored? `name` (for the name inside the file, not the file name!), `version` and `description` seem to work fine for me. You also want to change the filename?

**Comment by cschwan** [comment]
My bad, I didn't read it properly, which means I need a way to also rename the `.pc` file. Shall I open a separate issue?

**Comment by sdroege** [comment]
Best to open a separate issue for that, yes. Less confusing :)

**Comment by sdroege** [comment]
I'll take a look in the next days

**Comment by lu-zero** [comment]
The current cargo made supporting it much simpler.
