### ISSUE TITLE
Improve static build

### ISSUE THREAD

**Issue by cromefire** [lu-zero/cargo-c#174]
Based on the findings of rust-lang/rust#83143 it seems like a good Idea to add a `--static` flag or similar to automatically passes `-C target-feature=+crt-static` and also fail when there's no `--target` specified

**Comment by lu-zero** [comment]
Please test [this branch](https://github.com/lu-zero/cargo-c/pull/175)

**Comment by lu-zero** [comment]
It will be part of the next release.
