### ISSUE TITLE
Missing dll in target directory

### ISSUE THREAD

**Issue by jamrial** [lu-zero/cargo-c#18]
@dwbuiten

> [18:54:46] jamrial: Daemon404: i can't get rav1e to build a shared library after the crav1e merge
> [18:55:05] jamrial: cargo cbuild generates the header, the dll.a and the pkgconfig file, but no dll
> [18:55:26] Daemon404: that sounds like a bug
> [18:55:34] Daemon404: what about cargo cinstall --prefix=/whatever
> [18:55:49] Daemon404: the dll.a is generated while linking so that is really weird.
> [18:56:02] jamrial: does a build, then doesn't install anything (gives an error about file not found)
> [18:56:13] Daemon404: definitely a bug then
> [18:56:18] Daemon404: (havent tried on windows, someone else did
> [18:56:52] jamrial: also, the static library, which i expected would be called rav1e.a, seems to be called rust_out.lib
> [18:57:22] Daemon404: that's something else, possibly
> [18:57:47] Daemon404: are you on the GNU abi?
> [18:58:11] Daemon404: https://github.com/lu-zero/cargo-c/blob/master/src/main.rs#L159 <-- names should be right
> [18:58:33] Daemon404: i can fix it tomorrow morning (luca is away dying in 50C weather at some conf atm)
> [19:00:06] Daemon404: code doesnt look wrong, but it clearly must be
> [19:00:30] jamrial: yeah, using gnu and not msvc
> [19:01:13] jamrial: Daemon404: "let shared_lib = targetdir" the other lines are cfg.targetdir
> [19:01:16] jamrial: could be that
> [19:01:53] Daemon404: the other OS us targetdir
> [19:05:15] Daemon404: that + shared_object_link_args target dir may be the cultprit

$ cargo cbuild --release --prefix=/mingw64 && ls -l target/release/
drwxr-xr-x 1 jamrial None        0 Jun 27 19:16 build
drwxr-xr-x 1 jamrial None        0 Jun 27 19:20 deps
drwxr-xr-x 1 jamrial None        0 Jun 27 19:16 examples
drwxr-xr-x 1 jamrial None        0 Jun 27 19:16 incremental
-rw-r--r-- 1 jamrial None     2023 Jun 27 19:20 librav1e.d
-rw-r--r-- 2 jamrial None 11019828 Jun 27 19:20 librav1e.rlib
drwxr-xr-x 1 jamrial None        0 Jun 27 19:16 native
-rw-r--r-- 1 jamrial None      841 Jun 27 19:20 rav1e.def
-rw-r--r-- 1 jamrial None    18310 Jun 27 19:20 rav1e.dll.a
-rw-r--r-- 1 jamrial None    12246 Jun 27 19:20 rav1e.h
-rw-r--r-- 1 jamrial None      290 Jun 27 19:20 rav1e.pc
-rw-r--r-- 1 jamrial None  3139528 Jun 27 19:20 rust_out.lib

$ cargo cinstall --release --prefix=/mingw64
Already built
Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }

Also, although probably unrelated, the .pc file ignored the --prefix argument i passed to it:

$ grep prefix target/release/rav1e.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

**Comment by lu-zero** [comment]
The `pkg-config` generation has a local fix, I forgot to forward the paths while I integrated it.

For the `dll` problem, I need @dwbuiten help since I do not use windows.

**Comment by dwbuiten** [comment]
I'll look this afternoon.
