### ISSUE TITLE
Naming scheme for MSVC libraries breaks CMake Find Modules

### ISSUE THREAD

**Issue by amyspark** [lu-zero/cargo-c#181]
Hi,

While porting our use of [strukturag/libheif](https://github.com/strukturag/libheif) from MinGW GCC to MSVC 2015, I noticed the library doesn't detect a previous build of the rav1e encoder. As it turns out, the library was properly installed, but its object file library is not.

https://github.com/lu-zero/cargo-c/blob/094582f210cc59929024a04f5f9c0ddc29a3bca4/src/build_targets.rs#L62-L66

Those two lines should read `.lib` or `.a`, without the `.dll` suffix.

**Comment by 1480c1** [comment]
With mingw-w64 gcc the dll import library is `.dll.a` so the second one seems fine, the first one does need to be `.lib` without the `.dll` I think based on what I remember the naming convention for windows imp libraries.

**Comment by lu-zero** [comment]
If you can test and send a patch I'd apply it immediately.

**Comment by lu-zero** [comment]
Keep in mind that `rav1e.lib` is the static library. What is cmake expecting exactly?

**Comment by 1480c1** [comment]
`rav1e.lib`, confusingly, is also the name that msvc uses for dll import libraries 

https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#creating-an-import-library

**Comment by lu-zero** [comment]
from the little I read today it seems that there is no naming scheme, cmake even had an open issue about it both in producing and consuming them, but I couldn't see how they decided to resolve it.

**Comment by lu-zero** [comment]
After seeing https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake I wonder if it isn't just enough to add the `.dll.lib` to the options.

Alternatively for msvc the static variant could get `_static`. Let me know if either of the two works for you.

**Comment by nirbheek** [comment]
fwiw, meson does the following:

shared library with MSVC: `foo.dll`
shared library with MinGW: `libfoo.dll`
static library with MSVC: `libfoo.a`
static library with MinGW: `libfoo.a`
import library with MSVC: `foo.lib`
import library with MinGW: `libfoo.dll.a`

The only interesting thing here is that MSVC static libraries are called `libfoo.a`

The reasons are documented here: https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa

However, we also provide a way to override all this for each build target.

**Comment by lu-zero** [comment]
I tested on windows using `cmake.msi` provided by upstream and powershell.

I built rav1e using the `rav1e.cmd` script and then passed the `CMAKE_PREFIX_PATH` to the directory and it worked.
```
git clone https://github.com/strukturag/libheif
cd libheif/third-party
rav1e.cmd # you might want to use master so you do not have to figure out where is lib.exe
cd ..
mkdir .build
cd .build
cmake .. -DCMAKE_PREFIX_PATH=C:\<place>\libheif\third-party\rav1e\dist\
```

**Comment by lu-zero** [comment]
> fwiw, meson does the following:
> 
> shared library with MSVC: `foo.dll`
> shared library with MinGW: `libfoo.dll`
> static library with MSVC: `libfoo.a`
> static library with MinGW: `libfoo.a`
> import library with MSVC: `foo.lib`
> import library with MinGW: `libfoo.dll.a`
> 
> The only interesting thing here is that MSVC static libraries are called `libfoo.a`
> 
> The reasons are documented here: https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa
> 
> However, we also provide a way to override all this for each build target.

The choices for the names are mainly from upstream `cargo/rustc` itself so if we are going to change them would be better to try to get upstream on the same page.

@amyspark could you please provide more information? I plan to make a new cargo-c release soon and I'd like to have the msvc support fixed or documented.

**Comment by amyspark** [comment]
@lu-zero what would you need?

**Comment by lu-zero** [comment]
Tell me how to get to reproduce the problem, if it is still present after my fix in libheif :)

**Comment by amyspark** [comment]
Oh! Yes, it still happens with `--crt-static`, as the library is still named "rav1e.dll.lib" with MSVC.

Reproducing the issue is as easy as:

1. Downloading <https://github.com/xiph/rav1e/archive/v0.5.0-alpha.tar.gz>
2. Unpack rav1e.
3. With `rustup default stable-msvc`, issue `cargo cbuild --crt-static --release --prefix=Y:\our_root_folder --library-type=cdylib -j${SUBMAKE_JOBS}`.
4. Issue `cargo cinstall --crt-static --release --library-type=cdylib --prefix=Y:\our_root_folder`
5. Try configuring libheif with the "Visual Studio 16 2019" generator and a `CMAKE_PREFIX_PATH` of `Y:\our_root_folder`.

You should get this error:
```
  CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
CUSTOMBUILD : warning : MISSING PACKAGE [E:\krita-win\b_deps_msvc\ext_heif\ext_libheif.vcxproj]
  
    We only found some files of RAV1E, not all of them.  Perhaps your
    installation is incomplete or maybe we just didn't look in the right place?
    This package is NOT REQUIRED and you may ignore this warning but by doing
    so you may miss some functionality of libheif.

    Relevant CMake configuration variables:

      RAV1E_INCLUDE_DIR=E:/krita-win/i_deps_msvc/include/RAV1E
      RAV1E_LIBRARY=<not found>

    You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
    CMakeCache.txt to discard all values and force full re-detection if
    necessary.

  Call Stack (most recent call first):
    cmake/modules/FindRav1e.cmake:17 (libfind_process)
    CMakeLists.txt:73 (find_package)
```

**Comment by lu-zero** [comment]
>     4. Issue `cargo cinstall --crt-static --release --library-type=cdylib --prefix=Y:\our_root_folder`

Why are you using a `cdylib`? I'll try to reproduce the problem locally later.

**Comment by lu-zero** [comment]
Also: did you try
``` diff
diff --git a/cmake/modules/FindRav1e.cmake b/cmake/modules/FindRav1e.cmake
index 8c29672..5f24352 100644
--- a/cmake/modules/FindRav1e.cmake
+++ b/cmake/modules/FindRav1e.cmake
@@ -8,7 +8,7 @@ find_path(RAV1E_INCLUDE_DIR
 )

 find_library(RAV1E_LIBRARY
-    NAMES librav1e rav1e
+    NAMES librav1e rav1e rav1e.dll
     HINTS ${RAV1E_PKGCONF_LIBRARY_DIRS} ${RAV1E_PKGCONF_LIBDIR}
 )
```

It seems working here.

**Comment by amyspark** [comment]
> > ```
> > 4. Issue `cargo cinstall --crt-static --release --library-type=cdylib --prefix=Y:\our_root_folder`
> > ```
> 
> Why are you using a `cdylib`? I'll try to reproduce the problem locally later.

Because (apart from the static-vs-dynamic naming conflict) if I try to use the static library, libheif will fail linking because the Rust stdlib needs `-lws2_32`. It's not one of the [default](https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Modules/Platform/Windows-GNU.cmake#L29) [libraries](https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Modules/Platform/Windows-MSVC.cmake#L221) for CMake, and this requirement is only noticeable if someone uses pkg-config on Windows.

As for the edit to FindRav1e, I think it should work; I'll let you know.

**Comment by lu-zero** [comment]
`--crt-static` embeds everything in the static library, when I tried msvc happily linked it.

**Comment by lu-zero** [comment]
Upstream libheif accepted the other patch, if it works fine for you as well I'll add a note documenting how to make cmake FindLibrary and close the issue.

**Comment by amyspark** [comment]
@lu-zero Will test it again during the week, I'll let you know!

**Comment by amyspark** [comment]
@lu-zero we've got a libheif + deps upgrade incoming, I'll let you know hopefully during this week.

**Comment by amyspark** [comment]
It works! Thanks @lu-zero !

**Comment by carterbox** [comment]
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9046
