### ISSUE TITLE
Librsvg peculiarities

### ISSUE THREAD

**Issue by federicomenaquintero** [lu-zero/cargo-c#204]
I am filing this issue instead of concrete little bugs because I'm not sure how to match it with cargo-c's expectations.

I'm experimenting with the cargo-c configuration in librsvg/Cargo.toml to make it match the current scheme as closely as possible for things that are user-visible:

## pkg-config filename

Pkg-config file needs to be called `librsvg-2.0.pc` - I understand that #167 is a missing feature.

## SONAME vs. library name

 SONAME inside the ELF file needs to be `librsvg-2.so.2`.  This gets generated correctly if I put this in the configuration:

```
[package.metadata.capi.library]
name = "rsvg-2"
```
But unfortunately, using a hyphen instead of an underscore in the library name gives this:

```
$ cargo cbuild --prefix=/usr --libdir=/usr/lib64
    Finished dev [unoptimized + debuginfo] target(s) in 1m 01s
    Building pkg-config files
    Building pre-built header file
Error: CliError { error: Some(No such file or directory (os error 2)), exit_code: 101 }
```

If I have `name = "rsvg_2"` instead, the build succeeds, but the SONAME has an underscore instead of a hyphen which is wrong for librsvg.

## subdirectory name for header files

Librsvg will not use automatic generation of headers for now, as I haven't investigated how cbindgen behaves with it.

I put this in the configuration to disable header generation but enable putting `Cflags` in the `.pc` file (that field is empty otherwise):

```
[package.metadata.capi.header]
# This is so cargo-c will put the correct Cflags in the .pc file, otherwise it leaves them empty
enabled = true
# For now we have hand-written .h files, so disable generation of headers
generation = false
```

However, the `.pc` file uses an include path that does not match librsvg's current one:

Generated:
```
Libs: -L${libdir} -lrsvg-2
Cflags: -I${includedir}/rsvg-2
```

Expected:
```
Libs: -L${libdir} -lrsvg-2
Cflags: -I${includedir}/librsvg-2.0
```

## Versioned includes

GNOME has the convention that libraries put headers in `$(includedir)/libname-version/libname`, for example, `/usr/include/librsvg-2.0/librsvg/*.h`.  The double nesting is so that a) calling code can `#include <librsvg/rsvg.h>`, b) headers for multiple incompatible versions can be installed; c) it is all resolved by the include path output from pkg-config.

I am not sure if this is something that should go in the configuration, or just simulate it via `cargo cinstall --includedir=/usr/include/librsvg-2.0/librsvg`.

**Comment by lu-zero** [comment]
> I am filing this issue instead of concrete little bugs because I'm not sure how to match it with cargo-c's expectations.

Thank you for the report :)

> I'm experimenting with the cargo-c configuration in librsvg/Cargo.toml to make it match the current scheme as closely as possible for things that are user-visible:
> ## pkg-config filename
> 
> Pkg-config file needs to be called `librsvg-2.0.pc` - I understand that #167 is a missing feature.
> ## SONAME vs. library name
> 
> SONAME inside the ELF file needs to be `librsvg-2.so.2`. This gets generated correctly if I put this in the configuration:
> 
> ```
> [package.metadata.capi.library]
> name = "rsvg-2"
> ```
> 
> But unfortunately, using a hyphen instead of an underscore in the library name gives this:
> 
> ```
> $ cargo cbuild --prefix=/usr --libdir=/usr/lib64
>     Finished dev [unoptimized + debuginfo] target(s) in 1m 01s
>     Building pkg-config files
>     Building pre-built header file
> Error: CliError { error: Some(No such file or directory (os error 2)), exit_code: 101 }
> ```

This is a bug.

> If I have `name = "rsvg_2"` instead, the build succeeds, but the SONAME has an underscore instead of a hyphen which is wrong for librsvg.
> ## subdirectory name for header files
> 
> Librsvg will not use automatic generation of headers for now, as I haven't investigated how cbindgen behaves with it.
> 
> I put this in the configuration to disable header generation but enable putting `Cflags` in the `.pc` file (that field is empty otherwise):
> 
> ```
> [package.metadata.capi.header]
> # This is so cargo-c will put the correct Cflags in the .pc file, otherwise it leaves them empty
> enabled = true
> # For now we have hand-written .h files, so disable generation of headers
> generation = false
> ```
> 
> However, the `.pc` file uses an include path that does not match librsvg's current one:
> 
> Generated:
> 
> ```
> Libs: -L${libdir} -lrsvg-2
> Cflags: -I${includedir}/rsvg-2
> ```
> 
> Expected:
> 
> ```
> Libs: -L${libdir} -lrsvg-2
> Cflags: -I${includedir}/librsvg-2.0
> ```
> ## Versioned includes
> 
> GNOME has the convention that libraries put headers in `$(includedir)/libname-version/libname`, for example, `/usr/include/librsvg-2.0/librsvg/*.h`. The double nesting is so that a) calling code can `#include <librsvg/rsvg.h>`, b) headers for multiple incompatible versions can be installed; c) it is all resolved by the include path output from pkg-config.
> 
> I am not sure if this is something that should go in the configuration, or just simulate it via `cargo cinstall --includedir=/usr/include/librsvg-2.0/librsvg`.

I guess this and the previous could be addressed adding an override for the directory. in `package.metadata.capi.header`

**Comment by lu-zero** [comment]
https://github.com/lu-zero/cargo-c/pull/205 addresses most of the issues, the include paths can be addressed by the install feature that is being worked on or/and adding the override I mentioned.

**Comment by federicomenaquintero** [comment]
Thank you so much!

Do you think there will be a release soon?  GNOME's next release has alpha tarballs due on July 10, but I like to give distros and the GNOME release scripts a good amount of time to get their tooling ready.

I'm fine with rolling this out in stages - "build librsvg without libtool" can be the first one as soon as dashes in filenames work correctly.  I can copy the generated parts of the `.pc` file into librsvg's own template, to get the libraries right, and use the full generated version from cargo-c once it is ready.

**Comment by lu-zero** [comment]
After some night cursing I managed to get that part working on all the platforms, testing is welcome :)

We could discuss the best approach regarding the include path part today or tomorrow, it shouldn't be hard add you the configuration knobs for it, just we have to make sure they are right :)

**Comment by lu-zero** [comment]
Now cargo-c needs to learn about installing multiple headers and you should be set. If you could give it a look and tell me if it works as intended for your use-case would be great.

**Comment by federicomenaquintero** [comment]
Thanks!  I'll take a look.

**Comment by federicomenaquintero** [comment]
I still get `Error: CliError { error: Some(No such file or directory (os error 2)), exit_code: 101 }` :(

I wonder if you could give it a try on this branch?  https://gitlab.gnome.org/GNOME/librsvg/-/tree/cargo-c

**Comment by lu-zero** [comment]
Tell me how did you run cargo-c :)

**Comment by lu-zero** [comment]
I'm still working on the install support, hopefully I'll land the part you need soon and then work on the details on supporting the generation. Getting OUT_DIR when I need it is not simple.

**Comment by lu-zero** [comment]
With https://gitlab.gnome.org/lu-zero/librsvg/-/commit/17e2c5e53f575fe421f4178f8fe2359c53247660 and https://github.com/lu-zero/cargo-c/pull/212 it seems to produce the expected output, can you please confirm?

**Comment by federicomenaquintero** [comment]
Indeed it does, thank you!  I've cherry-picked your commit into my librsvg branch, and will push a rebased version ASAP.

Also, thanks for adding a way to override the .pc filename; I'm using that as well.

Can you please release 0.9 with that version number soon?  I'd like to update our configure script to test for that version explicitly; right now it just tests for the presence of the cargo-c binaries.

**Comment by lu-zero** [comment]
The release 0.9.0 is now out :)

**Comment by federicomenaquintero** [comment]
:tada: :tada: :tada: Thank you!!!

**Comment by federicomenaquintero** [comment]
I'm doing librsvg's conversion to meson and cargo-c at the same time, and all is going well.  Closing this!
