### ISSUE TITLE
Regression in 0.9.2: Requires a "capi" feature in the crate

### ISSUE THREAD

**Issue by sdroege** [lu-zero/cargo-c#221]
If you try building any of the gst-plugins-rs plugins with 0.9.2 it fails, e.g.

```console
cargo cbuild --manifest-path=text/regex/Cargo.toml 
Error: CliError { error: Some(Package `gst-plugin-regex v0.8.0 (/home/slomo/Projects/rust/gst-plugin-rs/text/regex)` does not have the feature `capi`), exit_code: 101 }
```

0.9.1 worked fine.

**Comment by sdroege** [comment]
My guess would be https://github.com/lu-zero/cargo-c/commit/93b5c8aaf2a931a8fd5b33881e3b7b7637fbccca

**Comment by sdroege** [comment]
Actually it's 1c40987dd83ba32b28c209b8227a45425d475c88 according to `git bisect` :)

**Comment by lu-zero** [comment]
I can add a warning and make it work for now. But you have to have the `capi` feature in the crate for the workspace support to work in the future.

**Comment by sdroege** [comment]
Thanks, I'll add that.

**Comment by lu-zero** [comment]
It is documented you must have the `capi` feature since v0.7.0 (see 0d5266f7a254b0608d1be8c48e0c030fda61dd92).

**Comment by sdroege** [comment]
It was working fine until 0.9.1 though.

**Comment by sdroege** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/543 FWIW.

**Comment by sdroege** [comment]
Thanks for the fast response in any case :)

**Comment by sdroege** [comment]
Let's close this then?

**Comment by lu-zero** [comment]
Sure, I'd not land the patch since int interferes with the set I'm working on for the next cargo release.

**Comment by sdroege** [comment]
No problem from my side :)
