### ISSUE TITLE
Compilation fails with linker error "undefined reference to `git_branch_name_is_valid'"

### ISSUE THREAD

**Issue by jamrial** [lu-zero/cargo-c#224]
As the subject says, compilation of cargo-c v0.9.2+cargo-0.55 fails when linking the final executables, using rustc 1.54.0 (a178d0322 2021-07-26) on an msys2 environment. A simple `cargo install cargo-c` yields the following error:

`K:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Jamrial\AppData\Local\Temp\cargo-installd4DEZy\release\deps\libgit2-ba888a354f46023c.rlib(git2-ba888a354f46023c.git2.dff6l7x8-cgu.14.rcgu.o):git2.dff6l7x8-cgu.:(.text+0xc95): undefined reference to 'git_branch_name_is_valid'`

Adding --locked to the install command makes it succeed.

**Comment by lu-zero** [comment]
You should open the issue with upstream https://github.com/rust-lang/git2-rs, they had a release 5 days ago, I assume the problem is there.

**Comment by lu-zero** [comment]
Is it still a problem with the current master?

**Comment by jamrial** [comment]
Yes. I updated to rust 1.55.0 (c8dfcfe04 2021-09-06) then tried to re-install cargo-c, and the same error occurs.

**Comment by lu-zero** [comment]
Did you report it upstream?

**Comment by jamrial** [comment]
No, after compiling with --locked, and considering it was a recent regression, i forgot about it and assumed it would eventually be fixed in git2-rs.

I'll do it later.

**Comment by lu-zero** [comment]
Can you please confirm it is not a problem anymore? I'd make a release in the next days.

**Comment by jamrial** [comment]
I just tried to install cargo-c without --locked and it worked, so it seems to have been fixed.
