### ISSUE TITLE
Windows implib contains wrong name

### ISSUE THREAD

**Issue by dwbuiten** [lu-zero/cargo-c#23]
When using `Wl,--out-implib,libwhatever.dll.a`, the DLL name embedded in the implib is whatever the linker is outputting to. For example, with rav1e, we generate `librav1e.dll.a` but the name embedded in this implib is `rav1e-<hash>.dll`, since this is how Rust names things.

The solution, as far as I can work out, is to *not* use `-Wl,--out-implib`, but to generate the implic based off the `.def` file we also generate, and specifying the correct DLL name when doing so, using `dlltool` (or `<prefix>-dlltool`), which is part of the standard MinGW toolchain.

This can be done after thinking like this:

`dlltool -d /path/to/rav1e.def -l /path/to/librav1e.dll.a -D rav1e.dll`

With an optional `-m <arch>` if needed (only if using a toolchain that requires `-m`, which I don't think we do anyway).

I'm not so sure how to execute post-link steps in `main.rs` from a quick skim.

**Comment by jamrial** [comment]
> For example, with rav1e, we generate librav1e.dll.a but the name embedded in this implib is rav1e-<hash>.dll, since this is how Rust names things.

This wasn't the case until a recent change. The dll generated didn't have the hash suffix, and linking would work as intended.

**Comment by lu-zero** [comment]
I can guide you if we want to go the `dlltool` way.
