### ISSUE TITLE
install bin targets too

### ISSUE THREAD

**Issue by dvc94ch** [lu-zero/cargo-c#234]
sorry if I missed it, but perusing the docs I didn't see it mentioned. would be nice to be able to install some cli utilities with the library.

**Comment by lu-zero** [comment]
Which kind of binaries you'd want to build? 

Keep in mind that _functionally_ it will not be different from calling `cargo install` if you mean Rust binaries. the RUSTFLAGS must change and thus all the dependencies would be rebuilt.

Building and installing C binaries might be in-scope of this project but it is a fair amount of work.

**Comment by dvc94ch** [comment]
I don't think there is a way to make `cargo install` install it at a custom location. I'm currently using it to install my c library in `/opt/` and the library loads data files in a binary format. There's a cli tool to convert the text format to the binary format that the library loads. This would be handy to create tarballs in ci without messing around too much, although cargo install and cp from .cargo could also work.

**Comment by lu-zero** [comment]
There is :)

From `cargo help install` since `cargo install --help` is not clear about it:

```
       This command manages Cargo's local set of installed binary crates. Only packages which have executable [[bin]] or [[example]] targets can be
       installed, and all executables are installed into the installation root's bin folder.

       The installation root is determined, in order of precedence:

       o  --root option

       o  CARGO_INSTALL_ROOT environment variable

       o  install.root Cargo config value <https://doc.rust-lang.org/cargo/reference/config.html>

       o  CARGO_HOME environment variable

       o  $HOME/.cargo
```

**Comment by dvc94ch** [comment]
ah missed it. I guess I'll close the issue then.
