### ISSUE TITLE
Upload regular release packages to GitHub for v0.9.5 release

### ISSUE THREAD

**Issue by EwoutH** [lu-zero/cargo-c#235]
The [v0.9.5](https://github.com/lu-zero/cargo-c/releases/tag/v0.9.5) has other release assets uploaded than other releases. It would be nice if they could be consistently named with earlier releases.

**Comment by lu-zero** [comment]
It was due the deploy CI failing due github being quite peculiar lately...

**Comment by lu-zero** [comment]
It should be fixed now.
