### ISSUE TITLE
Support Android Targets

### ISSUE THREAD

**Issue by leleliu008** [lu-zero/cargo-c#248]
```bash
cargo install cargo-c
cargo cinstall -vv --release --target armv7-linux-androideabi --prefix /home/fpliu/.ndk-pkg/install.d/rav1e/armeabi-v7a
```

thread 'main' panicked at 'not implemented: The target android- is not supported yet', /home/fpliu/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cargo-c-0.9.7+cargo-0.59/src/install.rs:90:18

**Comment by leleliu008** [comment]
```
cargo cbuild -vv --release --target armv7-linux-androideabi --prefix /home/fpliu/.ndk-pkg/install.d/rav1e/armeabi-v7a
```
this command can be run successfully. but `--prefix` options has no effect.

**Comment by lu-zero** [comment]
Sorry for the delay, looks like a bug was introduced while refactoring the library support.
