### ISSUE TITLE
cargo-c encodes full library version in install name on Darwin

### ISSUE THREAD

**Issue by carlocab** [lu-zero/cargo-c#249]
Hi there, I'm a Homebrew maintainer and we package two libraries built with cargo-c: rav1e and libimagequant.

I noticed that the dylibs that cargo-c builds encodes the full library version in the library's install name:
```
❯ otool -L "$(brew --prefix rav1e)/lib/librav1e.dylib"
/usr/local/opt/rav1e/lib/librav1e.dylib:
        /usr/local/opt/rav1e/lib/librav1e.0.5.1.dylib (compatibility version 0.0.0, current version 0.5.1)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
❯ otool -L "$(brew --prefix libimagequant)/lib/libimagequant.dylib"
/usr/local/opt/libimagequant/lib/libimagequant.dylib:
        /usr/local/opt/libimagequant/lib/libimagequant.0.0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```
In particular, `librav1e`'s install name ends in `librav1e.0.5.1.dylib`, while `libimagequant`'s ends in  `libimagequant.0.0.0.dylib`.

This is an issue because any software that links with `librav1e` or `libimagequant` will need to be recompiled even with just patch-level changes to the library's version. See, for example, Homebrew/homebrew-core#74289. This is usually quite wasteful, since changes in the patch version (or even minor version) typically don't require rebuilding dependent software because the newer version is almost always binary-compatible.

I'll mention here that I don't use Rust, so I don't know if this behaviour is inherited from `cargo`. However, given that `cargo-c` provides an abstraction layer for building C ABI libraries, I'd imagine this is something that might be productively handled here even if it is something that comes from `cargo`.

CC @barrbrain in case you have thoughts here.

**Comment by lu-zero** [comment]
cargo-c sets the linker line so we can make it embed the right information.
```
            let line = format!("-Wl,-install_name,{1}/lib{0}.{2}.{3}.{4}.dylib,-current_version,{2}.{3}.{4},-compatibility_version,{2}",
                    lib_name, libdir.display(), major, minor, patch);
```

 Can you please double check #250 and tell me if it working for you?

**Comment by carlocab** [comment]
Thanks for working on a fix so quickly. Let me test it by this weekend and let you know.

**Comment by lu-zero** [comment]
If it works for you I'd land it and bake a new bugfix release.

**Comment by carlocab** [comment]
My apologies; this slipped my mind. I'm building cargo-c from your branch now to try it out.

**Comment by carlocab** [comment]
Seems to work exactly as intended:
```
❯ otool -L */target/x86_64-apple-darwin/debug/*.dylib
libimagequant-4.0.0/target/x86_64-apple-darwin/debug/libimagequant.dylib:
        /usr/local/lib/libimagequant.0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
rav1e-0.5.1/target/x86_64-apple-darwin/debug/librav1e.dylib:
        /usr/local/lib/librav1e.0.5.dylib (compatibility version 0.5.0, current version 0.5.1)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```
Thanks so much!
