### ISSUE TITLE
cargo install cargo-c error

### ISSUE THREAD

**Issue by PlopTheReal** [lu-zero/cargo-c#266]
error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
  --> /home/marc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/core/compiler/build_plan.rs:81:35
   |
81 |         for arg in cmd.get_args().iter() {
   |                                   ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/marc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/core/compiler/mod.rs:757:24
    |
757 |     rustdoc.get_args().iter().any(|flag| {
    |                        ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `hash` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/marc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/util/rustc.rs:354:20
    |
354 |     cmd.get_args().hash(&mut hasher);
    |                    ^^^^ method not found in `impl Iterator<Item = &OsString>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cargo` due to 3 previous errors
error: failed to compile `cargo-c v0.9.10+cargo-0.62`, intermediate artifacts can be found at `/tmp/cargo-install7gJenw`

System: Ubuntu 22
Cargo version:  cargo 1.62.0 (a748cf5a3 2022-06-08)

**Comment by sdroege** [comment]
See https://github.com/rust-lang/cargo/issues/10803

**Comment by lu-zero** [comment]
Lovely, luckily it should be already solved upstream. The version support 0.63 is pretty much ready.

**Comment by PlopTheReal** [comment]
great! Updated with `cargo install cargo --force ` and then it worked well!
