### ISSUE TITLE
Consider naming DLLs built with MinGW as `libfoo.dll`

### ISSUE THREAD

**Issue by nirbheek** [lu-zero/cargo-c#280]
DLLs built with Autotools (which uses MinGW of course) are named `libfoo.dll`, and other build systems on Windows that use MSVC (like Visual Studio project files or CMake) use `foo.dll`.

So this is a convenient way to differentiate between DLLs built with MSVC and those built with MinGW, which is convenient for projects that provide binaries built with both toolchains. This is also what Meson does.

Would you like to follow Meson in this or do you prefer sticking with Cargo defaults as to which target platforms prefix `lib` to the library name?

**Comment by lu-zero** [comment]
I think would be nice to give the users the choice, that way it should be less confusing. Possibly we could tie more settings to a `--meson` cli option.

**Comment by nirbheek** [comment]
Yeah there's other behaviours also that Meson has, such as [always naming static libraries `libfoo.a` even when built with MSVC](https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa) and import libraries are always `foo.lib` so that `-lfoo` works in pkg-config files with GCC, off the top of my head.

AFAICT cargo-c uses `foo.lib` for static archives and `foo.dll.lib` for import libraries?

**Comment by lu-zero** [comment]
We can double check, windows is not a platform I use.

**Comment by lu-zero** [comment]
Is this still a problem?

**Comment by nirbheek** [comment]
Yes. We hack around it by [renaming the files after install](https://gitlab.freedesktop.org/gstreamer/cerbero/-/blob/74b9ebcea7c4f3d457f610b7e6bc5eb6d80f5094/recipes/gst-plugins-rs.recipe#L142-154).

**Comment by lu-zero** [comment]
I guess it is a good time to add this additional bit of logic then

**Comment by lu-zero** [comment]
@nirbheek do you have time to help me on this?

**Comment by amyspark** [comment]
Hey @lu-zero , @nirbheek just sent this over to me. I'll be taking a look into it later today.

**Comment by lu-zero** [comment]
Great! there are a couple of meson-parity issues that I keep postponing since I do not have access to windows... Feel free to message on irc in case.
