### ISSUE TITLE
Request: Enhance the CLI options.

### ISSUE THREAD

**Issue by stephan57160** [lu-zero/cargo-c#294]
Currently building a lib for Linux and also for Android.
Here comes the fun part:
- Linux requires versioning = true
- Android requires versioning = false
Soon, the same lib will be built for Windows, but I did try that part, at the moment, and then, I don't 
really know how this will be handled.

Of course, I can manage with a simple SED and "patch" my project Cargo.toml to set versioning=true|false
according to real target.

But, I also see 2 possibilities:
- Offer the possibility to override the Cargo.toml settings via some CLI options.
- Accept an option to specify a configuration file (Cargo-linux.toml, Cargo-whatever.toml, ...), also via some CLI options.
Both offer more flexibility, when a lib is supposed to be built for different targets.

**Comment by stephan57160** [comment]
Issue linked with #295.

**Comment by lu-zero** [comment]
the android and standard linux targets are already differently managed.

**Comment by lu-zero** [comment]
Also you should not use that configuration option at all. 
It is not doing what you think it is doing and probably we should document it better.

If you pass the right target to --target it will produce the correct library for system use for that target out of box.

**Comment by stephan57160** [comment]
The request was more "generic", not only for this particular option (versioning).
I'm used to tools and commands with a bunch of configuration options available on the CLI itself.

For "versioning", yes, it may require better documentation, as I understand now.

**Comment by lu-zero** [comment]
Your request is not clear. cargo-c has plenty of options and most of them are shared with cargo itself. 
Those options can be overridden by the normal means of cargo.

**Comment by lu-zero** [comment]
I guess this issue can be closed or there is something left to be addressed?
