### ISSUE TITLE
C appli fails to link with a RS lib built with versioning = false

### ISSUE THREAD

**Issue by stephan57160** [lu-zero/cargo-c#295]
Created a small C testing tool using a small RUST lib, built with cargo-c
`cargo-c` is the last official crate version.

I configure Cargo.toml with `versioning = true`:
* both build fine
* the C testing tool is able to link with the RS lib.

But when `versioning = false`, the C testing tool link fails with:
```
xxx: error while loading shared libraries: libxxxx.so.0: cannot open shared object file: No such file or directory
make[1]: *** [Makefile:43 : all] Erreur 127
```

As there is no `libxxxx.so.0` at all, I ran `readelf`:
```
stephan@PC2-Stephan:~/git/libreceipt-rs$ readelf -d production/linux/lib/libreceiptrs.so 

Dynamic section at offset 0x47808 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libxxxx.so.0]           # <-- has a SO version !!
 0x000000000000000c (INIT)               0x5000
 ```

With `pathelf`, if I replace the SONAME with `libxxxx.so`, the link succeeds.

**Comment by lu-zero** [comment]
I guess we should document better the expectation, making so if versioning is false the link line uses the plain libname.so is easy but if you used it to install the library in the system you are in for lots of fun surprises =/

**Comment by stephan57160** [comment]
> if you used it to install the library in the system you are in for lots of fun surprises =/
Not soon, but one day ... maybe.

No doubt that, "fun surprises" will bring you fun as well :-)

**Comment by lu-zero** [comment]
Not really, `versioning = false` expects you to not install the library as a system one, trying to do that is unsupported and would subtly break anything using such library.

Probably we could rename it to `plugin` or such so the intention is clear.

**Comment by stephan57160** [comment]
I can try that tomorrow ... at least, just to have some fun :-)

**Comment by lu-zero** [comment]
You stated how the breakage happens, I'd rather not enable people to do something wrong if I can.

**Comment by sdroege** [comment]
See https://github.com/lu-zero/cargo-c/pull/296

**Comment by stephan57160** [comment]
Thx

**Comment by eli-schwartz** [comment]
> You stated how the breakage happens, I'd rather not enable people to do something wrong if I can.

Well, it appears you did anyway. :)

(That's all right though, since both doing it, and refraining from doing it, will enable people to do something wrong.)
