### ISSUE TITLE
New Release with --debug?

### ISSUE THREAD

**Issue by seddonm1** [lu-zero/cargo-c#305]
Hi @lu-zero 

As described in this issue https://github.com/lu-zero/cargo-c/issues/302 which fixes the `--debug` option could you please make  a point release? This is very useful when developing as some of our release builds are extremely slow.

**Comment by JaydenElliott** [comment]
Agreed, this feature would help me also.

**Comment by lu-zero** [comment]
The next cargo will be released in ~2 days and cargo-c will follow. I hope it is fine for you :)

**Comment by seddonm1** [comment]
No worries. Two days is not a problem. Thanks a lot @lu-zero 😁
