### ISSUE TITLE
Segmentation fault with vendored-openssl feature

### ISSUE THREAD

**Issue by quietvoid** [lu-zero/cargo-c#309]
Hello, I'm trying to figure out what's happening with the cargo-c package on Arch Linux and found that the package was using `--all-features` when building, which seems to cause a segfault.
I've posted some info here: https://bugs.archlinux.org/task/77373

The related backtrace: https://0x0.st/oC1n.txt

So far I've been able to use `cargo cbuild` only when:
- installing with `cargo install cargo-c`
- building the Arch package without `--all-features`

I'm still confused as to what the problem is. Building a working cargo-c and using it also seems to make the non-working binaries work again.
So it might be deeper in `cargo` itself.

**Comment by lu-zero** [comment]
Do not build it with --all-features, Arch should have a good openssl in its system, does `cargo` with features=vendored-openssl show the same problem?

**Comment by quietvoid** [comment]
> does cargo with features=vendored-openssl show the same problem?

Yes, in fact it does.

**Comment by lu-zero** [comment]
It is worth reporting, but I would suggest you to depend on the system openssl on Arch nonetheless ^^;

**Comment by quietvoid** [comment]
Yes, this is something the Arch package maintainer should be fixing.
I'll move this to the `cargo` repo, thanks!
