### ISSUE TITLE
Consider enabling GitHub Discussions

### ISSUE THREAD

**Issue by realmazharhussain** [lu-zero/cargo-c#318]
I have a question and I don't see any links to a discussion platform where I would ask it. Many projects have some sort of an official discussion platform (e.g. a Matrix chatroom, a discord server, a Discourse forum, GitHub Discussions, etc.).

I can use the issue tracker for this purpose if that is the project's preferred way to hold discussions. But a discussion platform (e.g. GitHub Discussions) seems like a more appropriate place for this.

**Comment by lu-zero** [comment]
There is a [zulip stream](https://rust-av.zulipchat.com/#narrow/stream/254255-cargo-c) for it linked in the readme. 

I can try to make it more evident, but that's one of the supported communication channel. I can enable the discussion feature as well since I guess it is the easier place to reach.
