### ISSUE TITLE
Exit with proper error code on compilation failure

### ISSUE THREAD

**Issue by mgeier** [lu-zero/cargo-c#32]
First of all, thanks for this great tool!

I was trying to run `cargo cbuild` on Travis-CI, but the problem was that even though the compilation failed, no error was reported.

It looks like `cargo cbuild` returns exit code 0 (= success) when compilation fails.

**Comment by lu-zero** [comment]
Thank you for spotting the problem, I'll try to address it tomorrow :)

**Comment by lu-zero** [comment]
It should work now.

**Comment by mgeier** [comment]
Thanks a lot for the quick fix, it indeed works nicely!

When I have an error in a PR, I now get this on Travis-CI (using the `master` branch of `cargo-c`):

```
...
...
Error: Kind(InvalidInput)

The command "cargo cbuild --release" exited with 1.
...
...
Done. Your build exited with 1.
```

... and Travis-CI correctly reports it as a build error.

Are there any plans for a new release including this fix?

**Comment by lu-zero** [comment]
I tried to land another couple of fixed before a release but probably I can bump it now since the problem I'm working on happens only on nightly for now.

**Comment by lu-zero** [comment]
It should be on crates.io now, let me know if you find other bugs :)

**Comment by mgeier** [comment]
Perfect, it works, thank you!
