### ISSUE TITLE
LTO does not work due to default rlib target, causing extremely large static build artifacts

### ISSUE THREAD

**Issue by Humandoodlebug** [lu-zero/cargo-c#322]
In order to fix https://github.com/lu-zero/cargo-c/issues/138, `CrateType::Lib` is always selected when building (see [here](https://github.com/lu-zero/cargo-c/commit/596c582deed419b0cf1f80b9be77ff705df20e01#diff-be833857e8bbf63e2cbb12410f1e722789c4dce3d8c1dde47a79af89e52c71dcR113)). Unfortunately, this means LTO configuration is ignored (see [this cargo issue](https://github.com/rust-lang/cargo/issues/2301)), meaning our gstreamer plugins are ridiculously large, especially for static builds (hundreds of megabytes when they should be less than ten).

Reverting 596c582deed419b0cf1f80b9be77ff705df20e01 does fix it, however this would probably break https://github.com/lu-zero/cargo-c/issues/138.

**Comment by sdroege** [comment]
Thanks for finding this. I've added that also to the [GStreamer Rust tracker issue](https://gitlab.freedesktop.org/gstreamer/cerbero/-/issues/381).

Would it be possible to only build the rlib when the test target is selected? cargo-c should know that, right?

**Comment by lu-zero** [comment]
Yes and yes, thank you for debugging it :)

**Comment by sdroege** [comment]
@Humandoodlebug When statically linking multiple GStreamer Rust plugins, are you not running into https://github.com/rust-lang/rust/issues/44322#issuecomment-1310211971 ?

**Comment by lu-zero** [comment]
One annoyance is that it might again require rebuilding everything twice.

**Comment by lu-zero** [comment]
The upstream open issue is https://github.com/rust-lang/cargo/issues/4611

**Comment by Humandoodlebug** [comment]
Thank you for fixing this so quickly :)
@sdroege we haven't hit that yet, but we almost certainly will soon - thanks for the heads up.
