### ISSUE TITLE
Switch to some alternatives for `impl Executor for Exec`

### ISSUE THREAD

**Issue by weihanglo** [lu-zero/cargo-c#324]
The `Executor` trait was never meant to use as a public API. A pull request from who wrote that tries to remove it (rust-lang/cargo#11428).

I looked into the usage in this repo. It seems that the most outstanding usage is suppressing some message from rustc. Really sorry that at this moment I cannot foresee any possible alternatives. Is it good for you if Cargo removes the API in the next few versions? 

https://github.com/lu-zero/cargo-c/blob/8421f2da07cd066d2ae8afbb027760f76dc9ee6c/src/build.rs#L825-L835

**Comment by lu-zero** [comment]
It would break completely what I'm doing there and it is not suppressing messages but recover the `native-static-libs` from cargo.

**Comment by weihanglo** [comment]
I see. Thank you for your promptly response! I'll keep it there until we find a better approach.
