### ISSUE TITLE
Request: support module definition files and/or version scripts

### ISSUE THREAD

**Issue by amyspark** [lu-zero/cargo-c#335]
Hi,

I was looking into minimizing the symbol export footprint of our plugins, and was wondering if it could be possible to strip all exports except for a shortlist. This is commonly done in Windows with module definition files, or version scripts (GCC/Clang only).

Would it be possibly to add this? Or should it be addressed manually with `-C link-args`?

**Comment by lu-zero** [comment]
it seems more a question for upstream rustc or cargo, you might ask on zulip and see if there is something brewing in this regard.

**Comment by amyspark** [comment]
I've addressed it locally with a mix of `link-args` and `staticlib` postprocessing. Thanks!
