### ISSUE TITLE
Project lib compilation failure with Rust 1.38

### ISSUE THREAD

**Issue by jamrial** [lu-zero/cargo-c#34]
> $ cargo cbuild --release
>        Fresh autocfg v0.1.6
>        Fresh semver-parser v0.7.0
>        Fresh unicode-xid v0.1.0
>        Fresh cc v1.0.45
>        Fresh unicode-xid v0.2.0
>        Fresh lazy_static v1.4.0
>        Fresh cfg-if v0.1.10
>        Fresh rustc-demangle v0.1.16
>        Fresh nodrop v0.1.13
>        Fresh scopeguard v1.0.0
>        Fresh quick-error v1.2.2
>        Fresh regex-syntax v0.6.12
>        Fresh unicode-width v0.1.6
>        Fresh nasm-rs v0.1.3 (F:\msys\home\jamrial\rav1e\crates\nasm_rs)
>        Fresh encode_unicode v0.3.6
>        Fresh bitstream-io v0.8.4
>        Fresh either v1.5.3
>        Fresh y4m v0.4.0
>        Fresh semver v0.9.0
>        Fresh crossbeam-utils v0.6.6
>        Fresh thread_local v0.3.6
>        Fresh humantime v1.3.0
>        Fresh textwrap v0.11.0
>        Fresh itertools v0.8.0
>        Fresh ivf v0.1.0 (F:\msys\home\jamrial\rav1e\ivf)
>        Fresh winapi-x86_64-pc-windows-gnu v0.4.0
>        Fresh proc-macro2 v0.4.30
>        Fresh libc v0.2.62
>        Fresh rustc_version v0.2.3
>        Fresh proc-macro2 v1.0.4
>        Fresh arrayvec v0.4.11
>        Fresh crossbeam-queue v0.1.2
>        Fresh bitflags v1.2.0
>        Fresh log v0.4.8
>        Fresh serde v1.0.101
>        Fresh byteorder v1.3.2
>        Fresh num-traits v0.2.8
>        Fresh winapi v0.3.8
>        Fresh quote v0.6.13
>        Fresh backtrace-sys v0.1.31
>        Fresh memchr v2.2.1
>        Fresh num_cpus v1.10.1
>        Fresh quote v1.0.2
>        Fresh clap v2.33.0
>        Fresh num-integer v0.1.41
>        Fresh bincode v1.2.0
>        Fresh syn v0.15.44
>        Fresh time v0.1.42
>        Fresh winapi-util v0.1.2
>        Fresh backtrace v0.3.38
>        Fresh atty v0.2.13
>        Fresh syn v1.0.5
>        Fresh aho-corasick v0.7.6
>        Fresh synstructure v0.10.2
>        Fresh num-derive v0.2.5
>        Fresh chrono v0.4.9
>        Fresh memoffset v0.5.1
>        Fresh wincolor v1.0.2
>        Fresh clicolors-control v1.0.1
>        Fresh regex v1.3.1
>        Fresh proc-macro-hack v0.5.9
>        Fresh proc-macro-error v0.2.6
>        Fresh synstructure v0.12.0
>        Fresh serde_derive v1.0.101
>        Fresh arg_enum_proc_macro v0.3.0
>        Fresh failure_derive v0.1.5
>        Fresh crossbeam-epoch v0.7.2
>        Fresh termcolor v1.0.5
>        Fresh paste-impl v0.1.6
>        Fresh console v0.9.0
>        Fresh scan_fmt v0.2.4
>        Fresh err-derive v0.1.6
>        Fresh failure v0.1.5
>        Fresh crossbeam-deque v0.7.1
>        Fresh env_logger v0.6.2
>        Fresh paste v0.1.6
>        Fresh better-panic v0.2.0
>        Fresh vergen v3.0.4
>        Fresh rayon-core v1.6.0
>        Fresh pretty_env_logger v0.3.1
>        Fresh rayon v1.2.0
>    Compiling rav1e v0.1.0 (F:\msys\home\jamrial\rav1e)
>      Running `rustc --edition=2018 --crate-name rav1e 'src\lib.rs' --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 -C debuginfo=2 --crate-type staticlib --crate-type cdylib --cfg cargo_c -C 'link-arg=-Wl,--output-def,F:\msys\home\jamrial\rav1e\target\release\rav1e.def' --cfg 'feature="better-panic"' --cfg 'feature="binaries"' --cfg 'feature="clap"' --cfg 'feature="default"' --cfg 'feature="ivf"' --cfg 'feature="nasm"' --cfg 'feature="nasm-rs"' --cfg 'feature="pretty_env_logger"' --cfg 'feature="scan_fmt"' --cfg 'feature="signal-hook"' --cfg 'feature="signal_support"' --cfg 'feature="y4m"' -C metadata=21c2158ecae3626d -C extra-filename=-21c2158ecae3626d --out-dir 'F:\msys\home\jamrial\rav1e\target\release\deps' -L 'dependency=F:\msys\home\jamrial\rav1e\target\release\deps' --extern 'arg_enum_proc_macro=F:\msys\home\jamrial\rav1e\target\release\deps\arg_enum_proc_macro-e27e1973c4765719.dll' --extern 'arrayvec=F:\msys\home\jamrial\rav1e\target\release\deps\libarrayvec-85b1e69a1dfe2b91.rmeta' --extern 'backtrace=F:\msys\home\jamrial\rav1e\target\release\deps\libbacktrace-ba723d26412f4824.rmeta' --extern 'better_panic=F:\msys\home\jamrial\rav1e\target\release\deps\libbetter_panic-b40ae9c03f453acb.rmeta' --extern 'bincode=F:\msys\home\jamrial\rav1e\target\release\deps\libbincode-78bef8aded5e387b.rmeta' --extern 'bitstream_io=F:\msys\home\jamrial\rav1e\target\release\deps\libbitstream_io-423942a3214c1cf3.rmeta' --extern 'clap=F:\msys\home\jamrial\rav1e\target\release\deps\libclap-9be0a87917c0bce5.rmeta' --extern 'err_derive=F:\msys\home\jamrial\rav1e\target\release\deps\err_derive-8c345c4965004f0b.dll' --extern 'itertools=F:\msys\home\jamrial\rav1e\target\release\deps\libitertools-536cc6cf57170a5b.rmeta' --extern 'ivf=F:\msys\home\jamrial\rav1e\target\release\deps\libivf-900899ed971ede08.rmeta' --extern 'libc=F:\msys\home\jamrial\rav1e\target\release\deps\liblibc-5ce6a1bc33620a60.rmeta' --extern 'log=F:\msys\home\jamrial\rav1e\target\release\deps\liblog-1d510bdb1caecc48.rmeta' --extern 'num_derive=F:\msys\home\jamrial\rav1e\target\release\deps\num_derive-6d918bb3d3b8ee8a.dll' --extern 'num_traits=F:\msys\home\jamrial\rav1e\target\release\deps\libnum_traits-8efb1d5d0fb02579.rmeta' --extern 'paste=F:\msys\home\jamrial\rav1e\target\release\deps\libpaste-68528407a37bee89.rmeta' --extern 'pretty_env_logger=F:\msys\home\jamrial\rav1e\target\release\deps\libpretty_env_logger-995b89978e064b7b.rmeta' --extern 'rayon=F:\msys\home\jamrial\rav1e\target\release\deps\librayon-4a0a58bd414003ce.rmeta' --extern 'scan_fmt=F:\msys\home\jamrial\rav1e\target\release\deps\libscan_fmt-614d837afbaf1ee3.rmeta' --extern 'serde=F:\msys\home\jamrial\rav1e\target\release\deps\libserde-dcf393b412529984.rmeta' --extern 'serde_derive=F:\msys\home\jamrial\rav1e\target\release\deps\serde_derive-7faed31b84f47287.dll' --extern 'y4m=F:\msys\home\jamrial\rav1e\target\release\deps\liby4m-e28e508283a5b483.rmeta' -L 'F:\msys\home\jamrial\rav1e\target\release\build\rav1e-d9902951bced4110\out' -l static=rav1easm -L 'native=F:\msys\home\jamrial\rav1e\target\release\build\backtrace-sys-c4c236cb8f225f30\out' -L 'native=C:\Users\jamrial\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'`
> error: crate `log` required to be available in rlib format, but was not found in this form
> 
> error: crate `libc` required to be available in rlib format, but was not found in this form
> 
> error: crate `num_traits` required to be available in rlib format, but was not found in this form
> 
> error: crate `bitstream_io` required to be available in rlib format, but was not found in this form
> 
> error: crate `arrayvec` required to be available in rlib format, but was not found in this form
> 
> error: crate `bincode` required to be available in rlib format, but was not found in this form
> 
> error: crate `rayon` required to be available in rlib format, but was not found in this form
> 
> error: crate `itertools` required to be available in rlib format, but was not found in this form
> 
> error: crate `paste` required to be available in rlib format, but was not found in this form
> 
> error: aborting due to 9 previous errors
> 
> error: Could not compile `rav1e`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --edition=2018 --crate-name rav1e 'src\lib.rs' --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 -C debuginfo=2 --crate-type staticlib --crate-type cdylib --cfg cargo_c -C 'link-arg=-Wl,--output-def,F:\msys\home\jamrial\rav1e\target\release\rav1e.def' --cfg 'feature="better-panic"' --cfg 'feature="binaries"' --cfg 'feature="clap"' --cfg 'feature="default"' --cfg 'feature="ivf"' --cfg 'feature="nasm"' --cfg 'feature="nasm-rs"' --cfg 'feature="pretty_env_logger"' --cfg 'feature="scan_fmt"' --cfg 'feature="signal-hook"' --cfg 'feature="signal_support"' --cfg 'feature="y4m"' -C metadata=21c2158ecae3626d -C extra-filename=-21c2158ecae3626d --out-dir 'F:\msys\home\jamrial\rav1e\target\release\deps' -L 'dependency=F:\msys\home\jamrial\rav1e\target\release\deps' --extern 'arg_enum_proc_macro=F:\msys\home\jamrial\rav1e\target\release\deps\arg_enum_proc_macro-e27e1973c4765719.dll' --extern 'arrayvec=F:\msys\home\jamrial\rav1e\target\release\deps\libarrayvec-85b1e69a1dfe2b91.rmeta' --extern 'backtrace=F:\msys\home\jamrial\rav1e\target\release\deps\libbacktrace-ba723d26412f4824.rmeta' --extern 'better_panic=F:\msys\home\jamrial\rav1e\target\release\deps\libbetter_panic-b40ae9c03f453acb.rmeta' --extern 'bincode=F:\msys\home\jamrial\rav1e\target\release\deps\libbincode-78bef8aded5e387b.rmeta' --extern 'bitstream_io=F:\msys\home\jamrial\rav1e\target\release\deps\libbitstream_io-423942a3214c1cf3.rmeta' --extern 'clap=F:\msys\home\jamrial\rav1e\target\release\deps\libclap-9be0a87917c0bce5.rmeta' --extern 'err_derive=F:\msys\home\jamrial\rav1e\target\release\deps\err_derive-8c345c4965004f0b.dll' --extern 'itertools=F:\msys\home\jamrial\rav1e\target\release\deps\libitertools-536cc6cf57170a5b.rmeta' --extern 'ivf=F:\msys\home\jamrial\rav1e\target\release\deps\libivf-900899ed971ede08.rmeta' --extern 'libc=F:\msys\home\jamrial\rav1e\target\release\deps\liblibc-5ce6a1bc33620a60.rmeta' --extern 'log=F:\msys\home\jamrial\rav1e\target\release\deps\liblog-1d510bdb1caecc48.rmeta' --extern 'num_derive=F:\msys\home\jamrial\rav1e\target\release\deps\num_derive-6d918bb3d3b8ee8a.dll' --extern 'num_traits=F:\msys\home\jamrial\rav1e\target\release\deps\libnum_traits-8efb1d5d0fb02579.rmeta' --extern 'paste=F:\msys\home\jamrial\rav1e\target\release\deps\libpaste-68528407a37bee89.rmeta' --extern 'pretty_env_logger=F:\msys\home\jamrial\rav1e\target\release\deps\libpretty_env_logger-995b89978e064b7b.rmeta' --extern 'rayon=F:\msys\home\jamrial\rav1e\target\release\deps\librayon-4a0a58bd414003ce.rmeta' --extern 'scan_fmt=F:\msys\home\jamrial\rav1e\target\release\deps\libscan_fmt-614d837afbaf1ee3.rmeta' --extern 'serde=F:\msys\home\jamrial\rav1e\target\release\deps\libserde-dcf393b412529984.rmeta' --extern 'serde_derive=F:\msys\home\jamrial\rav1e\target\release\deps\serde_derive-7faed31b84f47287.dll' --extern 'y4m=F:\msys\home\jamrial\rav1e\target\release\deps\liby4m-e28e508283a5b483.rmeta' -L 'F:\msys\home\jamrial\rav1e\target\release\build\rav1e-d9902951bced4110\out' -l static=rav1easm -L 'native=F:\msys\home\jamrial\rav1e\target\release\build\backtrace-sys-c4c236cb8f225f30\out' -L 'native=C:\Users\jamrial\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'` (exit code: 1)
> Error: Kind(InvalidInput)

May be related to #33

**Comment by lu-zero** [comment]
It is. the easiest workaround is to add in the `Cargo.toml` the "staticlib" crate type. e.g.:

``` diff 
[lib]
 bench = false
+crate-type = ["lib", "staticlib"]
```

**Comment by lu-zero** [comment]
I guess we can live with the workaround for the time being.
