### ISSUE TITLE
Convert to github actions

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/cargo-c#35]
- [ ] Convert the travis.yml to github actions (linux)
- [ ] Add a window target
- [ ] Add a macOS target

**Comment by 1480c1** [comment]
Have you already signed up for github actions?

**Comment by lu-zero** [comment]
I did as organization, forgot to enable also my account, now it is as well.

**Comment by lu-zero** [comment]
#36 and #37 addressed it.
