### ISSUE TITLE
cinstall does not append prefix to relative libdir

### ISSUE THREAD

**Issue by xclaesse** [lu-zero/cargo-c#366]
`cargo cinstall --prefix=/opt/foo --libdir=lib --release --library-type cdylib --destdir=/home/xclaesse/root`

When running that command in gst-plugins-rs, I'm expecting installed libraries to go into `/home/xclaesse/root/opt/foo/lib`. However it seems to put them in `/home/xclaesse/root/lib`. 

Appending the prefix to destdir is what `meson install` or autotools typically do. Note that it's far from easy to get that right on Windows, be careful.

**Comment by xclaesse** [comment]
For reference implementation in python: https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/__init__.py

**Comment by lu-zero** [comment]
cargo-c correctly appends destdir to prefix, but it is not composing libdir with prefix even if it is not an absolute path.

**Comment by xclaesse** [comment]
@lu-zero ah that's possible, yes. When libdir is a relative path it should be made relative to prefix IMHO.

**Comment by lu-zero** [comment]
I'm seeing that meson prefixes `prefix` if `libdir` isn't absolute, I can copy the behavior.

**Comment by lu-zero** [comment]
@xclaesse if you could test it a bit would be great, otherwise I'll need some time in the weekend.
