### ISSUE TITLE
Fail to compile cargo-c v0.9.27+cargo-0.74.0 using Rust 1.76.0

### ISSUE THREAD

**Issue by rofferom** [lu-zero/cargo-c#378]
My project is still using Rust 1.76.0, and I'm currently targeting cargo-c 0.9.27 that used to be compatible with my toolchain version.

However since yesterday:

```error: failed to compile cargo-c v0.9.27+cargo-0.74.0, intermediate artifacts can be found at /tmp/cargo-installjIS1PX.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
  package cargo-util v0.2.12` cannot be built because it requires rustc 1.77 or newer, while the currently active rustc version is 1.76.0
  Try re-running cargo install with --locked
```

`cargo-util` 0.2.12 has been released yesterday and it requires at least Rust 1.77.0. Should `cargo-c` fix a specific version of `cargo-util` since it can introduce breaking changes ?

**Comment by sdroege** [comment]
You'll have to make use of the Cargo.lock that cargo-c 0.9.27 was released with, or get a fixed cargo (see https://github.com/rust-lang/cargo/issues/13873 etc).

**Comment by lu-zero** [comment]
you can use `cargo install --locked` or run `cargo update --precise` passing the correct cargo-util version you want.

**Comment by rofferom** [comment]
Thanks for your quick feedbacks, it fixed my issue :+1:
