### ISSUE TITLE
cargo-c v0.10.0 fails on Windows in the "Installing debugging information" step if there is no PDB file

### ISSUE THREAD

**Issue by wantehchang** [lu-zero/cargo-c#383]
This is a bug in cargo-c v0.10.0, introduced in https://github.com/lu-zero/cargo-c/commit/19ec991ebfcb32697b9099537e0a16af289fed01.

cargo-c version:

```
C:\src>cargo cinstall --version
cargo-c 0.10.0+cargo-0.80.0
```

On Windows, if the build does not produce a PDB file, cargo-c fails in the "Installing debugging information" step. This can be reproduced by building rav1e with the `--library-type=staticlib` option.

Here are the steps to reproduce the bug:

```
git clone -b v0.7.1 --depth 1 https://github.com/xiph/rav1e.git
cd rav1e
cargo cinstall --release --library-type=staticlib --prefix=/usr --destdir build
```

The build fails with the following error messages:

```
  Installing pkg-config file
  Installing header file
  Installing static library
  Installing debugging information
Error: CliError { error: Some(failed to copy `C:\src\rav1e\target\x86_64-pc-windows-msvc\release\rav1e.pdb` to `build\usr\bin\rav1e.pdb`

Caused by:
    The system cannot find the file specified. (os error 2)), exit_code: 101 }

```

The build succeeds if the `--library-type=staticlib` option is not passed to `cargo cinstall`.

**Comment by lu-zero** [comment]
https://github.com/lu-zero/cargo-c/pull/382 should address it, I'll prepare a point release in the next days

**Comment by wantehchang** [comment]
Great. Thanks! I forgot to check the pull requests.

**Comment by wantehchang** [comment]
I verified https://github.com/lu-zero/cargo-c/pull/382 fixed this issue.
