### ISSUE TITLE
Library is rebuilt when it shouldn't need to be

### ISSUE THREAD

**Issue by mwcampbell** [lu-zero/cargo-c#387]
If I run `cargo cbuild` followed by `cargo cinstall` with the same options, or repeatedly run either command, the library is rebuilt, even though it should only be built by the first invocation. Note that I'm including the `--release` option when invoking both `cargo cbuild` and `cargo cinstall`. This doesn't happen with the example-project project in the cargo-c repository, but I can consistently reproduce it on the cargo-c branch of the [accesskit-c](https://github.com/AccessKit/accesskit-c) repository. Any idea what weird thing about my library is breaking the logic that determines whether a rebuild is needed?

**Comment by mwcampbell** [comment]
I forgot to mention, this is on x86_64-unknown-linux-gnu.

**Comment by lu-zero** [comment]
Does cargo show the same behavior? In Gentoo we noticed that at least rustix somehow breaks the freshness checks, but I hadn't found the time to debug it further yet.

**Comment by mwcampbell** [comment]
No. If I repeatedly run `cargo cbuild --release`, it keeps rebuilding the crate, but if I run `cargo build --release` more than once, it doesn't rebuild after the first time.

**Comment by lu-zero** [comment]
```
❯ cargo cbuild -v
       Fresh objc2-encode v4.0.1
       Fresh arrayvec v0.7.2
       Fresh accesskit v0.16.0
       Fresh once_cell v1.19.0
       Fresh objc-sys v0.3.3
       Fresh immutable-chunkmap v2.0.5
       Fresh objc2 v0.5.1
       Fresh accesskit_consumer v0.24.0
       Fresh paste v1.0.12
       Fresh objc2-foundation v0.2.0
       Fresh objc2-app-kit v0.2.0
       Fresh accesskit_macos v0.17.0
       Dirty accesskit-c v0.12.0 (/Users/lu_zero/Sources/rust/accesskit-c): forced
   Compiling accesskit-c v0.12.0 (/Users/lu_zero/Sources/rust/accesskit-c)
     Running `/Users/lu_zero/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name accesskit --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=157 --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C link-arg=-Wl,-install_name,/usr/local/lib/libaccesskit.0.12.dylib,-current_version,0.12.0,-compatibility_version,0.12 -C link-arg=-Wl,-headerpad_max_install_names --cfg cargo_c --print native-static-libs --cfg 'feature="capi"' -C metadata=b4b52801ddb6d647 --out-dir /Users/lu_zero/Sources/rust/accesskit-c/target/aarch64-apple-darwin/debug/deps --target aarch64-apple-darwin -C incremental=/Users/lu_zero/Sources/rust/accesskit-c/target/aarch64-apple-darwin/debug/incremental -L dependency=/Users/lu_zero/Sources/rust/accesskit-c/target/aarch64-apple-darwin/debug/deps -L dependency=/Users/lu_zero/Sources/rust/accesskit-c/target/debug/deps --extern accesskit=/Users/lu_zero/Sources/rust/accesskit-c/target/aarch64-apple-darwin/debug/deps/libaccesskit-c9b795af8f4e1238.rlib --extern accesskit_macos=/Users/lu_zero/Sources/rust/accesskit-c/target/aarch64-apple-darwin/debug/deps/libaccesskit_macos-02bebd846f89bd10.rlib --extern paste=/Users/lu_zero/Sources/rust/accesskit-c/target/debug/deps/libpaste-67012df052d75c2b.dylib -C 'link-arg=-Wl,-install_name,@rpath/libaccesskit.dylib'`
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
    Building pkg-config files
  Populating uninstalled header directory
```
I see that definitely something is wrong seems that the FingerPrint information is never stored...

**Comment by lu-zero** [comment]
And it is never stored because it looks for `accesskit.h` that does not exist.

**Comment by mwcampbell** [comment]
We do generate the header using cbindgen, but we do so manually, outside of cargo cbuild, because we have to generate it with a nightly toolchain and commit the generated header to version control. Is there a better way to do this without breaking the freshness check?

**Comment by lu-zero** [comment]
The problem was in cargo-c, hopefully now solved.

**Comment by mwcampbell** [comment]
Yes, I confirmed that it's solved on the fix-header-fingerprinting branch.
