### ISSUE TITLE
Generate a CMake config module

### ISSUE THREAD

**Issue by segevfiner** [lu-zero/cargo-c#392]
By also generating a CMake config module (Probably with an imported target) and placing it in the right path in the resulting installation dir, the built library can be used directly by CMake `find_package` without the need for writing a wrapper find module using pkg-config (Which only works in Unix-like OSes) or otherwise searching for the files.

See https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html

**Comment by lu-zero** [comment]
I see [FindPkgConfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) exists and it seems available on windows via vcpkg, I wouldn't add special code for cmake or other additional build system.

**Comment by segevfiner** [comment]
😢
