### ISSUE TITLE
Impossibility to change the --prefix option on successive runs

### ISSUE THREAD

**Issue by Luni-4** [lu-zero/cargo-c#42]
If the command `cargo c-install --prefix=/my/second/dir` is run a second time with a different prefix, the prefix of the `.pc` file isn't changed. This problem seems related to this [condition](https://github.com/lu-zero/cargo-c/blob/2c27accfa03a4ebe8f03e1844878c177dee85a36/src/main.rs#L550)

**Comment by lu-zero** [comment]
It should work correctly now.

**Comment by Luni-4** [comment]
Yep, thanks a lot! :)
