### ISSUE TITLE
cbuild does not generate the shared library in the target/${profile}/ path

### ISSUE THREAD

**Issue by dbermond** [lu-zero/cargo-c#43]
`cbuild` does not generate the shared library. The shared library is generated only when running `cinstall`. Tested in rav1e with cargo-c 0.3.1.

Can this be changed so `cbuild` also generates the shared library?

**Comment by lu-zero** [comment]
`cbuild` generates the shared library, could you provide more information and `ls -alR target/*/` ?

**Comment by dbermond** [comment]
I'm using Arch Linux x86_64.
The rust version currently is 1.39.0.
cargo-c is installed on system and currently at version 0.4.0.

Steps used to build rav1e and the C library:
```
$ git clone https://github.com/xiph/rav1e.git
$ cd rav1e
$ cargo fetch
$ cargo build --release --frozen
$ cargo cbuild --release --prefix='/usr'
```



After this, the shared library is not generated. Here is the output of [`ls -alR target/*/`](https://paste.ee/p/WBHcU).

**Comment by lu-zero** [comment]
```
-rwxr-xr-x 1 user group 22116096 dez  6 20:53 librav1e-bfbf0e656d2012cb.so
```

It is built but not copied in the main directory. the `cargo rustc` override story is less than perfect, if you were expecting to have the `.so` in the target directory.

**Comment by dbermond** [comment]
Yes, I was expecting a clear output of `librav1e.so` (and the versioned library files) in the main directory, as with `cinstall`.

Thank you for clarifying this.

If this is a wontfix, fell free to close this issue.

**Comment by lu-zero** [comment]
It is an issue that requires to either fix `cargo rustc` or to switch to cargo-as-library and make the build time _LONG_.

**Comment by lu-zero** [comment]
Done in `0.6.0` (will be released today)
