### ISSUE TITLE
Support for excluding rust compiler_builtin from staticlib

### ISSUE THREAD

**Issue by Andarwinux** [lu-zero/cargo-c#431]
Some targets use llvm's compiler-rt by default, in which case cargo-c should exclude rust's compiler-rt from staticlib in order to use what the C toolchain provides. Otherwise it will increase the size or cause symbol conflicts.

Here's one way to hack it, but it's ugly.
```
llvm-ar t staticlib.a | grep '^compiler_builtins.*\.o$' | xargs -I {} llvm-ar d staticlib.a {}
```

**Comment by lu-zero** [comment]
Could you please provide more information? which are the targets? is there a rustc and cargo issue for the problem? Staticlibs are produced by rustc using its provided information.

**Comment by lu-zero** [comment]
you can tell the final linker invocation to gc what's redundant, but this is an issue for rustc to solve.
