### ISSUE TITLE
Request: provide the Cargo.lock file

### ISSUE THREAD

**Issue by dbermond** [lu-zero/cargo-c#44]
Please consider providing the `Cargo.lock` file. This file is important for making [reproducible builds](https://reproducible-builds.org/).

Without the lockfile, a given version of this project cannot be reproducible over time, as the dependencies will get updated. Using a lockfile with the `--locked` option in `cargo` commands (like `cargo build`) will ensure that the dependencies will not be updated, allowing the build to be reproducible. It can also prevent possible build problems in updated dependency versions.

A quote from the [`cargo install` documentation](https://doc.rust-lang.org/cargo/commands/cargo-install.html) better explains the importance of the lockfile:

> The --locked flag can be used to force Cargo to use the packaged Cargo.lock file if it is available. This may be useful for ensuring reproducible builds, to use the exact same set of dependencies that were available when the package was published. It may also be useful if a newer version of a dependency is published that no longer builds on your system, or has other problems.

**Comment by lu-zero** [comment]
Who cares about reproducible builds should store the `cargo vendor` output.

I consider the Cargo.lock purely annoying in the git tree.

I would accept patches that save the `Cargo.lock` as release artifact either by generating the tarballs manually or by just adding it as-is.
