### ISSUE TITLE
Cannot create shared libraries on BSDs

### ISSUE THREAD

**Issue by jbeich** [lu-zero/cargo-c#45]
DragonFly, FreeBSD, NetBSD, Solaris handle shared libraries similar to Linux. OpenBSD manage versioning themselves. A possible fix would be to make Linux (aka ELF) case a fallback for unknown systems.

```
$ cargo install cargo-c
$ git clone https://github.com/xiph/rav1e
$ cd rav1e; cargo cbuild
[...]
thread 'main' panicked at 'not yet implemented: The target freebsd- is not supported yet', src/main.rs:174:18
```
See also [downstream hack](https://github.com/freebsd/freebsd-ports/blob/cf31d6dad49e/devel/cargo-c/Makefile#L84).

**Comment by lu-zero** [comment]
If you can send a patch to add support for the systems you can test with would be great.

**Comment by jbeich** [comment]
As of v0.4.0 still fails on FreeBSD, see [librav1e log](https://github.com/lu-zero/cargo-c/files/3932222/librav1e-0.1.0_1.log). Given FreeBSD Ports are also used on DragonFly I can't remove the hack unless it's also fixed.

**Comment by lu-zero** [comment]
I do not have access to such systems right now, if you could please test and provide a patch would be great.

**Comment by jbeich** [comment]
Why did you leave the following line Linux-only? It's used by `cargo cinstall`.
https://github.com/lu-zero/cargo-c/blob/f634b6c2dea1d9cf7b98d14c32c36fe83c70d720/src/main.rs#L616

**Comment by lu-zero** [comment]
Because not having a system running I missed that, if you could send a patch with the additional lines would be great :) Otherwise I'll look into it Monday.

**Comment by jbeich** [comment]
Thanks. v0.5.1 [works fine](https://github.com/lu-zero/cargo-c/files/3972018/librav1e-0.1.0_1.log) without `s/linux/freebsd/` hack.
