### ISSUE TITLE
Update cbindgen dependency to 0.11

### ISSUE THREAD

**Issue by ignatenkobrain** [lu-zero/cargo-c#46]
Would be much appreciated so that we don't have to have 2 versions of cbindgen in Fedora.

**Comment by lu-zero** [comment]
Sure, if you have a patch I'll add it otherwise I'll fold the update with the BSD support update

**Comment by lu-zero** [comment]
I updated and made a release, I hope it works for you.

**Comment by ignatenkobrain** [comment]
Thanks. Much appreciated!
