### ISSUE TITLE
msvc support

### ISSUE THREAD

**Issue by Kleinrotti** [lu-zero/cargo-c#61]
I get the error message that windows-msvc is not supported. Is it possible to add support for msvc?

**Comment by lu-zero** [comment]
If somebody is willing to help sure. I do not use the windows platform so it is fairly difficult to me to write it.

**Comment by dwbuiten** [comment]
Is the use case to static link in an MSVC-compiled C/C++ binary? If you are OK with a linking to a DLL, currently, you can sitll use the Windows GNU ABI and generate an import library for the generated DLL that MSVC can use.

To be honest, I have been putting off installing MSVC and faffing around to test... I think @shssoichiro had a setup already?

**Comment by Kleinrotti** [comment]
I want to compile ffmpeg with msvc and link rav1e statically yes.

**Comment by lu-zero** [comment]
It should be potentially simple to add the support do you want to give it a try? :)

**Comment by shssoichiro** [comment]
@dwbuiten I don't currently have a Windows setup, although I have in the past and used MSVC for the Rust toolchain. I don't believe I've statically linked external libraries though, when I had to link ffmpeg in the past, I was able to install the Windows dll's and include files and dynamically link.
