### ISSUE TITLE
Add the ability to specify -application_extension linker flag

### ISSUE THREAD

**Issue by ePirat** [lu-zero/cargo-c#78]
In some cases it can be desired to use a library in a macOS/iOS Application extension which limits the available APIs. For the linker to check this and mark the resulting library as extension safe, I need to add `-application_extension` to the linker flags. (The clang flag for this is `-fapplication-extension`)

Here a snippet from the `ld` manpage:
```
-application_extension
                 Specifies that the code is being linked for use in an application extension.  The linker will then validiate that any dynamic libraries linked
                 against are safe for use in application extensions.
```

**Comment by lu-zero** [comment]
What are the shortcomings in always turn it on?

**Comment by ePirat** [comment]
If you use certain APIs not allowed in Application extensions, linking will fail.

**Comment by lu-zero** [comment]
Then setting the env to `RUSTFLAGS=-C link-arg=-Wl,-application_extension` should be enough. You need to pass the link flag to all the crates being build.
