### ISSUE TITLE
Install header without subdirectory

### ISSUE THREAD

**Issue by cschwan** [lu-zero/cargo-c#84]
First: Thanks a lot for making `cargo-c`! The complete installation of a C interface was something I felt missing from `cargo` and therefore is much appreciated!

Now to the question: Would it be possible to either
- install the header (are there situations where there can be multiple headers?) without a subdirectory, meaning at `${includedir}/project.h` instead of `${includedir}/project/project.h`, or to
- set `Cflags` inside the `.pc` file such that it points inside the directory?

In any case I would like to write `#include <project.h>` instead of `#include <project/project.h>` in my C or C++ program.

**Comment by lu-zero** [comment]
Multiple headers requires either cooperation with cbindgen (that currently does not support multiple-headers generation) or to implement the workspace support.

> set `Cflags` inside the `.pc` file such that it points inside the directory?

That's the current behavior

``` rust
            cflags: vec![format!("-I{}/{}", "${includedir}", name)],
```

**Comment by cschwan** [comment]
You're right, something must've been wrong with my configuration, but it works now. This can be closed. Thanks again!

**Comment by lu-zero** [comment]
No problem :)
