### ISSUE TITLE
cinstall: destdir path joining problems on Windows with absolute paths

### ISSUE THREAD

**Issue by lazka** [lu-zero/cargo-c#89]
I run 

```
cargo cinstall --release --frozen --library-type=cdylib --destdir=C:/foo
```

but things get installed into C:/usr:

```
C:/usr/
└── local
    ├── bin
    │   └── rav1e.dll
    ├── include
    │   └── rav1e
    │       └── rav1e.h
    └── lib
        ├── librav1e.dll.a
        ├── pkgconfig
        │   └── rav1e.pc
        └── rav1e.def
```

**Comment by lu-zero** [comment]
You should provide more information on which flavor of windows and how you are getting to this. I do not use windows so I'll need your help in tracking it down.

**Comment by 1480c1** [comment]
I think he uses windows with msys2, idk the windows version number

this is probably similar to the situation I mentioned in daala irc

**Comment by lazka** [comment]
yeah, under MSYS2. I worked it around for now by passing a relative prefix (which results in the wrong prefix in the .pc file, but that is ignored on Windows)

My guess is that when concatenating destdir with an absolute prefix only the prefix survives (destdir="C:/foo", prefix="C:/bar" -> "C:\bar")

**Comment by lu-zero** [comment]
please try to specify all of them and report back

**Comment by lazka** [comment]
> please try to specify all of them and report back

You mean prefix and destdir? `--destdir=C:/foo --prefix=C:/bar` -> things are written to `C:\bar`

**Comment by lu-zero** [comment]
without c:/

**Comment by lazka** [comment]
`--prefix=bar --destdir=foo` -> written to `./foo/bar`

**Comment by lu-zero** [comment]
who wants to make a patch to fix destdir joining :) ?

**Comment by 1480c1** [comment]
I'm assuming it's somewhere around here? https://github.com/lu-zero/cargo-c/blob/master/src/cinstall.rs#L54

**Comment by lazka** [comment]
my attempt :)

```rust
fn append_to_destdir(destdir: &PathBuf, path: &PathBuf) -> PathBuf {
    let mut components = path.components();
    while components.as_path().has_root() {
        components.next();
    }
    destdir.join(components.as_path())
}
```

**Comment by lu-zero** [comment]
Ideally you could skip only the `Component::Prefix(_)` using a patter match. That loop would strip too much

**Comment by lu-zero** [comment]
> I'm assuming it's somewhere around here? https://github.com/lu-zero/cargo-c/blob/master/src/cinstall.rs#L54

That's right, apparently it the case of prefix it should be stripped before stripping the `/`.

**Comment by lazka** [comment]
> Ideally you could skip only the `Component::Prefix(_)` using a patter match. That loop would strip too much

You need to remove Prefix (C:) and RootDir (/)

**Comment by lu-zero** [comment]
if it works the great :) please send a pull request

**Comment by dwbuiten** [comment]
It would need to match all drive letters, and not just C:, FWIW
